Use stricter version spec for the dependencies to avoir random regressions
Below an example of regression I have in my project without changing anything.

Since this is typically the result of loose dependency definitions, I tried to fork this project and use more strict dependencies, and this PR fixes it

    Error: Engine 'uglify' not found. Refusing to store configuration
        at /home/rossille/work/all-projects/stargate/node_modules/customize/index.js:176:15
        at /home/rossille/work/all-projects/stargate/node_modules/customize/node_modules/lodash/index.js:3395:24
        at /home/rossille/work/all-projects/stargate/node_modules/customize/node_modules/lodash/index.js:3073:15
        at baseForOwn (/home/rossille/work/all-projects/stargate/node_modules/customize/node_modules/lodash/index.js:2046:14)
        at Function.mapValues (/home/rossille/work/all-projects/stargate/node_modules/customize/node_modules/lodash/index.js:3394:9)
        at Customize.merge (/home/rossille/work/all-projects/stargate/node_modules/customize/index.js:173:32)
        at module.exports (/home/rossille/work/all-projects/stargate/node_modules/bootprint-base/index.js:7:18)
        at Customize.load (/home/rossille/work/all-projects/stargate/node_modules/customize/index.js:238:12)
        at module.exports (/home/rossille/work/all-projects/stargate/node_modules/bootprint-json-schema/index.js:6:6)
        at Customize.load (/home/rossille/work/all-projects/stargate/node_modules/customize/index.js:238:12)
        at bootprintSwagger (/home/rossille/work/all-projects/stargate/node_modules/bootprint-openapi/index.js:13:6)
        at Customize.load (/home/rossille/work/all-projects/stargate/node_modules/customize/index.js:238:12)
        at /home/rossille/work/all-projects/stargate/node_modules/customize-watch/index.js:51:34
        at /home/rossille/work/all-projects/stargate/node_modules/customize-watch/index.js:50:25
        at /home/rossille/work/all-projects/stargate/node_modules/customize-watch/index.js:50:25
        at Recustomize.run (/home/rossille/work/all-projects/stargate/node_modules/customize-watch/index.js:119:19)